;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-line-dwim
        beginning-of-visual-line
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        dabbrev-expand
        delete-horizontal-space
        electric-newline-and-maybe-indent
        end-of-visual-line
        helm-M-x
        helm-confirm-and-exit-minibuffer
        ido-switch-buffer
        indent-for-tab-command
        kill-region
        kill-visual-line
        mark-whole-buffer
        markdown-insert-bold
        mc/mark-next-line-like-this
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-kill-line
        org-metaright
        org-mouse-down-mouse
        org-self-insert-command
        org-shiftmetaright
        org-yank
        other-frame
        sgml-close-tag
        sgml-slash
        swiper
        text-scale-adjust
        transpose-words
        undo-tree-visualize
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        dired-unmark-backward
        markdown-exdent-or-delete
        ))
